version: "3"

services:
  node_db:
    container_name: node_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=node_live_db
      - POSTGRES_USER=pgadmin
      - POSTGRES_PASSWORD=12345
    volumes:
      - node_db_data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    ports:
      - "8080:8080"
    depends_on:
      - node_db
    environment:
      - PG_DB=node_live_db
      - PG_USER=pgadmin
      - PG_PASSWORD=12345
      - PG_HOST=node_db
    env_file:
      - .env/.env
volumes:
  node_db_data: {}
